# Generated by Django 3.2.4 on 2021-06-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_age', models.IntegerField()),
                ('student_dob', models.DateField()),
                ('student_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
